Description: >
  This templates deploys a linux bastion (ssh endpoint) inside provided VPC
  with two public subnets. The bastion will have an auto-scaling group.
  It will also create a log group

  Inspired by following example:
Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

    InstanceType:
        Description: Which Instance Type should be running the bastion
        Type: String
        Default: t2.micro
        AllowedValues:
          - t2.nano
          - t2.micro
          - t2.small

    VPC:
        Description: Choose which VPC these bastion hosts hould be deployed to
        Type: AWS::EC2::VPC::Id

    PublicSubnet:
        Description: Choose which public subnet these bastion hosts hould be deployed to
        Type: AWS::EC2::Subnet::Id

    SecurityGroup:
        Description: Select the Security Group that gives SSH Access
        Type: AWS::EC2::SecurityGroup::Id

    KeyPairName:
        Description: "Pub/Priv key pairs to allow a secure connection to the instance"
        Type: AWS::EC2::KeyPair::KeyName

Mappings:

    # These are the latest amazon linux 2 AMIs as of Jul 2018:
    AWSRegionToAMI:
        eu-west-3:
            AMI: ami-2cf54551 
        eu-west-2:
            AMI: ami-b8b45ddf
        eu-west-1:
            AMI: ami-466768ac
        eu-central-1:
            AMI: ami-7c4f7097

Resources:
  BastionMainLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 7

  SSHInvalidUser:
    Type: AWS::Logs::MetricFilter
    # A CloudWatch Metrich Filter to watch for 
    # failed ssh login attempts
    # Can be used for alarms
    Properties:
      LogGroupName: !Ref BastionMainLogGroup
      FilterPattern: "[Mon, day, timestamp, ip, id, status = Invalid, ...]"
      MetricTransformations:
        - MetricName: ssh_invalid_user
          MetricValue: '1'
          MetricNamespace: SSH

  BastionRole:
    Type: AWS::IAM::Role
    Properties:
      # It is good practice to add region to your role names
      # To distinguish them from each other in your account
      # since iam roles live Globaly in your account
      RoleName: !Sub ${EnvironmentName}-${AWS::StackName}Role-${AWS::Region}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action: 
              - sts:AssumeRole
      Path: "/"
      Policies:
        -
          PolicyName: bastion-s3-access
          # Access to s3 buckets
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              -
                Effect: Allow
                Action: 
                  - s3:GetObject
                  - s3:PutObject
                  - s3:AbortMultipartUpload
                  - s3:Listbucket
                  - s3:ListbucketMultipartUploads
                Resource: "*"
        -
          PolicyName: bastion-ec2-access
          # Gives acces to ElasticIp and Status
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              -
                Effect: Allow
                Action:
                  - ec2:AssociateAddress
                  - ec2:DescribeAddresses
                  - ec2:DescribeInstanceStatus
                Resource: "*"
        -
          PolicyName: bastion-log-access
          # Gives access to Create log group & stream if not exists
          # and push new logs if already not there
          # Restricted to only create it's own group and streams inside
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
                Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:GetLogEvents
                  - logs:PutLogEvents   
                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
                  - logs:PutRetentionPolicy
                  - logs:PutMetricFilter
                  - logs:CreateLogGroup
                Resource:
                  - !Join ["", ["arn:aws:logs:", !Ref 'AWS::Region', ":", !Ref 'AWS::AccountId', ":log-group:", !Ref BastionMainLogGroup]]
                  - !Join ["", ["arn:aws:logs:", !Ref 'AWS::Region', ":", !Ref 'AWS::AccountId', ":log-group:", !Ref BastionMainLogGroup, ":*:*"]]
        -
          PolicyName: bastion-ssm-access
          # Needed for SSM Agent 
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
                Effect: Allow
                Action:
                  - ssm:DescribeAssociation
                  - ssm:GetDeployablePatchSnapshotForInstance
                  - ssm:GetDocument
                  - ssm:GetManifest
                  - ssm:GetParameters
                  - ssm:ListAssociations
                  - ssm:ListInstanceAssociations
                  - ssm:PutInventory
                  - ssm:PutComplianceItems
                  - ssm:PutConfigurePackageResult
                  - ssm:UpdateAssociationStatus
                  - ssm:UpdateInstanceAssociationStatus
                  - ssm:UpdateInstanceInformation
                Resource: "*"
        -
          PolicyName: bastion-ec2messages-access
          # Deployment messaging for status, etc
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
                Effect: Allow
                Action:
                  - ec2messages:AcknowledgeMessage
                  - ec2messages:DeleteMessage
                  - ec2messages:FailMessage
                  - ec2messages:GetEndpoint
                  - ec2messages:GetMessages
                  - ec2messages:SendReply
                Resource: "*" 



  BastionHostProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: 
        - !Ref BastionRole
      Path: "/"

  ElasticIp:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  BastionHost:
    Type: AWS::EC2::Instance
    Metadata: 
      AWS::CloudFormation::Init: 
        config: 
          packages: 
            yum:
              python2-pip: []
              python3-pip: []
              awslogs: []
          files:
            "/etc/awslogs/config/sshlogs.conf":
              content: !Sub |
                [general]
                state_file= /var/awslogs/agent-state
                [/var/log/secure]
                file = /var/log/secure
                log_group_name = ${BastionMainLogGroup}
                log_stream_name = {instance_id}/ssh.log
                datetime_format = %d/%b/%Y:%H:%M:%S
              mode: '000400'
              owner: "root"
              group: "root"
            "/etc/cfn/cfn-hup.conf":
              content: !Sub |
                [main]
                stack= ${AWS::StackId}
                region=${AWS::Region}
              mode: "000400"
              owner: "root"
              group: "root"
            "/etc/cfn/hooks.d/cfn-auto-reloader.conf":
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.BastionHost.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource BastionHost --region ${AWS::Region}
          commands: 
            installawscli:
              command: "pip install awscli --ignore-installed six"
              ignoreErrors: true
            updateawslogconf:
              command: !Sub "sed -i s/log_group_name.*/log_group_name=${BastionMainLogGroup}/g /etc/awslogs/awslogs.conf"
              ignoreErrors: true
            updateawscliconf:
              command: !Sub "sed -i s/us-east-1/${AWS::Region}/g /etc/awslogs/awscli.conf"
              ignoreErrors: true
            restartawslogs:
              command: "systemctl restart awslogsd.service"
              ignoreErrors: true

    Properties: 
      SubnetId: !Ref PublicSubnet 
      KeyName: !Ref KeyPairName
      ImageId:  !FindInMap [AWSRegionToAMI, !Ref 'AWS::Region', AMI]
      InstanceType: !Ref InstanceType
      SecurityGroupIds:
          - !Ref SecurityGroup
      IamInstanceProfile: !Ref BastionHostProfile
      UserData:
        "Fn::Base64":
          !Sub |
            #!/bin/bash
            # Get the latets cf package
            yum update -y aws-cfn-bootstrap
            # Start cfn-init
            /opt/aws/bin/cfn-init -v --region ${AWS::Region} --stack ${AWS::StackName} --resource BastionHost
            # Start cfn-up daemon - listens to changes for the instances metadata
            /opt/aws/bin/cfn-hup &> /dev/null
            # All done, sending signal
            /opt/aws/bin/cfn-signal -e $? --region ${AWS::Region} --stack ${AWS::StackName} --resource BastionHost
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName} bastion host with amazonlinux2"
        - Key: CreatedBy
          Value: Cloudformation
    CreationPolicy:
      # How long to wait for the instance to report back successfully
      ResourceSignal:
        # 5Minutes
        Timeout: PT5M
  
Outputs: 
  BastionIP:
      Description: Public IP for the bastion
      Value: !GetAtt BastionHost.PublicIp

  CloudWatchLogs:
    Description: CloudWatch Logs GroupName. SSH Logs and instance logs will be streamed here
    Value: !Ref BastionMainLogGroup

